### ISSUE TITLE
[TODO] Allow destroying dev environment from vessel CLI

### ISSUE THREAD

**Issue by fideloper** [Vessel-App/vessel-cli#12]
Allowing users to start over if there is an error. This needs an annoying prompt to help prevent automated abuse. Preferably it outputs what it is  about to delete as well (esp the content of `~/.ssh/config` it might remove)

- [ ] Delete `vessel.yml`
- [ ] Delete `~/.vessel/<project-name>`
- [ ] Delete `~/.ssh/config` entry (is this dangerous?)
- [ ] Delete the Fly application
